### ISSUE TITLE
Player Build

### ISSUE THREAD

**Issue by jeffaroundtheworld** [jeffaroundtheworld/2024gamecollab#15]
Work together to create the player scene.  Start first with the mechanics... you should be able to use ideas from the marble maze player code (written code is on Moodle for the 11s). 

Consider for the horror style game that you might want to be able to look up and down as well and left and right... see if you can figure out how to rotate camera up and down while maintaining the ability to walk.

There is a blank level 1 scene where you could instantiate a player for testing.

**Comment by ajleach9689** [comment]
https://www.youtube.com/watch?v=A3HLeyaBCq4 
working through this tutorial currently. To get a basic movement we can work with.

**Comment by jeffaroundtheworld** [comment]
Basic player movement is looking good.
