### ISSUE TITLE
Level Design

### ISSUE THREAD

**Issue by jeffaroundtheworld** [jeffaroundtheworld/2024gamecollab#17]
First... decide if you are going to use a pre-built level or just existing assets that you are going use to design your own world.

Start collecting assets for your level design in preparation for collab with the story design team (for the actual designing of the levels).

**Comment by Rhyswatsonn** [comment]
https://sketchfab.com/3d-models/abandon-building-b5710eb5fb7a4c6e9d0ebe73fa72adee
https://sketchfab.com/3d-models/abandon-hospital-6d2fe758dad34e24a86c088ae24ddb80
https://sketchfab.com/3d-models/abandoned-hospital-part-two-c4c2546533fd4ee2a87ddd642f33f446
https://sketchfab.com/3d-models/old-warehouse-62e1bedf57bd46238798be1578490676

Here are some cool models i found that we could use/take inspiration from. do you guys wanna use assets online or make out own

**Comment by ZachLife** [comment]
I think we should use some premade models and we can build off them

**Comment by Jackcarlisle1** [comment]
https://sketchfab.com/3d-models/abandoned-hospital-part-one-8461ff4cbf23429ebbc49388305a8b9d

this one best imo

**Comment by jeffaroundtheworld** [comment]
Found another that might be of interest.... mostly exterior with an empty interior so you could create your own walls, rooms, and floors.

[https://skfb.ly/oOOQH](https://skfb.ly/oOOQH)

**Comment by jeffaroundtheworld** [comment]
Looks like well underway with collecting assets and basic decisions
