### ISSUE TITLE
Background Music

### ISSUE THREAD

**Issue by jeffaroundtheworld** [jeffaroundtheworld/2024gamecollab#21]
Find 3 pieces of background music/ambience to set the tone for your game.  Put them in a music folder on the repo.

**Comment by JackV13** [comment]
https://www.youtube.com/watch?v=aW9wBjkpWIE
Another one. Which one do we like more?

**Comment by JackV13** [comment]
sounds good. hear is a good creaking door noise for later. 
https://www.youtube.com/watch?v=W2jJpBouh9U

**Comment by ediehouston** [comment]
We should find a noise that the enemies can make to like alert you that they are nearby and it can get louder when they get closer.

**Comment by ediehouston** [comment]
I just don't know what that would sound like yet.

**Comment by jeffaroundtheworld** [comment]
Can we pick some background music and then open a new issue for sound effects?
