### ISSUE TITLE
Sketch out the school

### ISSUE THREAD

**Issue by jeffaroundtheworld** [jeffaroundtheworld/2024gamecollab#22]
Have a look at the [Story Design Issue Thread](https://github.com/jeffaroundtheworld/2024gamecollab/issues/18) to get an idea of where the narrative is heading in the game.  Then check out the [this resource](https://book.leveldesignbook.com/process/overview) from the Level Design Book.  Start making a 2D sketch of the school with different rooms and possible interactions.

As there are people in afternoon and morning team.... figure out a way to break up the design process (perhaps allocate different floors or locations to different groups?).

Don't be afraid to reach out to @mya1919 @kodriq @ediehouston to clarify details, make suggestions, and see how the story is developing.

**Comment by ZachLife** [comment]
heres a model of what I think the above ground part of the school could be
https://a360.co/3P2Qhbw
![20240301_185611](https://github.com/jeffaroundtheworld/2024gamecollab/assets/72240526/aee05b58-30ba-4fc9-af00-9e3112098558)

**Comment by kodriq** [comment]
yeah I think the hospital being underneath a decent part of it would be a cool mechanic because it having the same layout as (parts of) the school would be interesting, but we would have to figure out where to put the stairs

**Comment by ZachLife** [comment]
I'll definitely add textures while I create a detailed model but I'll keep everything changeable

**Comment by jeffaroundtheworld** [comment]
@ZachLife - sounds good.  Hoping to have all the levels in at least a navigable stage after Spring Break so that we can start adding story elements and NPC interactions.

Try playing the Hospital Part 3 scene to see where we are currently at.
