### ISSUE TITLE
Hospital gltf missing from repo

### ISSUE THREAD

**Issue by jeffaroundtheworld** [jeffaroundtheworld/2024gamecollab#27]
Tried to open the Hospital prt1 scence on the repo and got the following error:
![image](https://github.com/jeffaroundtheworld/2024gamecollab/assets/48102368/c9746ced-84ed-452a-b07f-36b01386dc41)

make sure the scene.gltf is in the repo and pushed.

**Comment by Rhyswatsonn** [comment]
im not sure what happend to my assets and i can seem to find them. i will redo this soon. @Jackcarlisle1 i heard you maybe started adding meshes to the first part of the hospital? do you still have this? lmk thanks

**Comment by jeffaroundtheworld** [comment]
Looks like @Jackcarlisle1 fixed this and started in new branch
