### ISSUE TITLE
Hospital Part 2 is Godot Project

### ISSUE THREAD

**Issue by a-longe** [jeffaroundtheworld/2024gamecollab#34]
It looks like the Hospital Part 2 Folder that was added was created as a it's own project, not as a separate scene.

Because of this, Godot seems to skip over loading it into the file system, so I cant seem to load it directly from the project but instead have to load a new instance of Godot to view it.

Instead, move the scene files out of the HOSPITAL PART 2 directory and into the base project folder.

**Comment by jeffaroundtheworld** [comment]
Discussed with morning team.  Now fixed in main
