### ISSUE TITLE
Three Player Scripts

### ISSUE THREAD

**Issue by a-longe** [jeffaroundtheworld/2024gamecollab#42]
I looks like there are three player controllers in the project, is there a reason for this?
Looks like character_2.gd was made by Dylan and Player.gd was made by Zorien.

There's also a edit_character_3.gd that seems to be a remnant of not using git to test, looks like it can be removed.

**Comment by jeffaroundtheworld** [comment]
Looks like @Dylanimal cleaned this up... @Dylanimal, make sure you close issues after you have completed them
