### ISSUE TITLE
Repo Clean Up

### ISSUE THREAD

**Issue by a-longe** [jeffaroundtheworld/2024gamecollab#44]
It looks like we need to clean up the repo a bit, 

As of right now there are 3 seperate directories with texture assets in them and in the "Place setting images here" directory,
It says that the plan was to keep all the textures and images in the same place.

There is also a driectory called Level design that has all three hospital parts with a seperate directory that's called HOSPITAL PART 2. Is this a copy of the directory found in the Level Design directory called abandoned_hospital_part_two?

I think there needs to be some discussion on what the project layout will be.
Where will all the scenes be found? (in one directory?)
Are you going to keep the textures in the same place regardless of what scene they're in or are you keeping them in separate directories depending on the scene they're from?

The issue could be coming from the merge functionality of git, as merging a branch into another one will not remove any files.

**Comment by Rhyswatsonn** [comment]
i will clean up all the level design clutter right now but someone else who is working on the player should clean that stuff up

**Comment by a-longe** [comment]
Looks good Rhys!

Maybe Zorien and Dylan could talk about which player controller to use?
