### ISSUE TITLE
Hospital Part 2 Collision Shape QA

### ISSUE THREAD

**Issue by jeffaroundtheworld** [jeffaroundtheworld/2024gamecollab#47]
Wander through all parts of the Hospital level as the player and ensure that you don't get stuck anywhere.  The Trimesh Collision Shape can be fairly complicated and sometimes leads to impossible "pockets" that the player can't get out of OR is a steep angle that the player doesn't think of as floor so can't jump off of.

For Instance, I consistently get stuck at this position on Part 3:
![image](https://github.com/jeffaroundtheworld/2024gamecollab/assets/48102368/c48caa16-2473-4dd9-885d-2681328cd324)

Solution could be to delete a part of the collision shape if not needed or to add a simplified collision shape (like a boxshape) so the "pocket doesn't exist.

**Comment by JackV13** [comment]
There is a red door in hospital part 2 that when you run into it the entire screen just goes completely black.
