### ISSUE TITLE
Inventory Mechanic

### ISSUE THREAD

**Issue by jeffaroundtheworld** [jeffaroundtheworld/2024gamecollab#51]
Design inventory system for the player so that they can keep track of what they have collected (flashlight, key, papers, weapon, etc...).

Inventory system should be done as a scene that can be added as a node to the player.

**Comment by ajleach9689** [comment]
Update: 
Working through : https://www.youtube.com/watch?v=V79YabQZC1s 
Trying to simplify it as there a a ton of features we don't need
