### ISSUE TITLE
Sound Effects

### ISSUE THREAD

**Issue by jeffaroundtheworld** [jeffaroundtheworld/2024gamecollab#53]
Comb through the Jamboard and **make a list** of all the potential sound effects needed (eg: clicking of flashlight, opening of door, jingle of keys, calling of friend).  Then collect all of those sounds and place them in the Audio folder of the repo.

**Comment by jeffaroundtheworld** [comment]
@Rhyswatsonn here is the Youtube Downloader App.... just unzip and run as shown.

[https://drive.google.com/file/d/1z7WpqbJ2Q6CwhGwvyO_kM0q4_W9qtZ--/view?usp=sharing](url)

**Comment by ediehouston** [comment]
In the story there's a part where the protagonist hears faint yelling from her friend. So that could be one.

**Comment by ediehouston** [comment]
Then maybe a sound effect for picking things up (equipping the flashlight, picking up paper documents)

**Comment by ediehouston** [comment]
In our vision that we've mapped out there's a part where the floor breaks so that will need a sound as well.

**Comment by Rhyswatsonn** [comment]
kk sounds good thanks ill look for thoose

**Comment by kodriq** [comment]
I think we might also need footsteps, as we might be having one enemy on the floor above

**Comment by jeffaroundtheworld** [comment]
sounds look good
