### ISSUE TITLE
Player Climb Ladder

### ISSUE THREAD

**Issue by jeffaroundtheworld** [jeffaroundtheworld/2024gamecollab#64]
There is a ladder on Hospital Part 2 that Story team wants to use as the final exit.  Can you develop a player mechanic so that when you are on the ladder and press forward, you climb the ladder rather than move forward?

I am thinking of an Area3D collision shape over the ladder so that on_body_enter switches a player variable called "climbing" to true and when you step away (with "S" key) then on_body_exit triggers climbing to be false.

**Comment by Dylanimal** [comment]
I have it working now but the code is pretty bad. Alex will review the code.
