### ISSUE TITLE
Stairs and ladder doesn't work 

### ISSUE THREAD

**Issue by zorienm** [jeffaroundtheworld/2024gamecollab#72]
I think someone may have moved the whole map up or down and committed it  so now the stairs and ladder's don't work, or it may be something else.

**Comment by mya1919** [comment]
stairs should be fixed on hospital part two 
the other levels are not yet but im trying to fix them

**Comment by Dylanimal** [comment]
Adding stairs renamed the hospital part two file which the ladder code relied on, so easy fix and should work now.
