### ISSUE TITLE
write dialogue

### ISSUE THREAD

**Issue by kodriq** [jeffaroundtheworld/2024gamecollab#76]
We need to decide where there will be any text or dialogue (like the context), and write it out so i can add it to my code + if we need to add it to the intro or smth
(BTW anyone can contribute)

**Comment by kodriq** [comment]
https://docs.google.com/document/d/1J2e7z2q7t8qqVhHyUEu-oBtlRowRzhIOAwEnTjQcDGE/edit?usp=sharing

heres a link to a shared google doc we can write on ^^

**Comment by ediehouston** [comment]
Also feel free to edit what I put on the doc for the intro dialogue

**Comment by kodriq** [comment]
https://www.dafont.com/splendid66.font
this is the font im using for the dialogue
