### ISSUE TITLE
monster/enemy sound effects

### ISSUE THREAD

**Issue by kodriq** [jeffaroundtheworld/2024gamecollab#87]
I didn't see an issue for this and it looks like we need it
Something to tell you its chasing you, and maybe ambient noises if you are nearby it?

**Comment by zorienm** [comment]
https://tuna.voicemod.net/sound/d00fd7d5-7d01-456a-b668-db0a00fd4337
https://www.soundboard.com/sb/thelastofusclickersoundss
I thinking of these two sounds
