### ISSUE TITLE
Add "Go Back" feature for all of the doors that transport you to the next level.

### ISSUE THREAD

**Issue by jeffaroundtheworld** [jeffaroundtheworld/2024gamecollab#93]
Add "Go Back" feature for all of the doors that transport you to the next level....

At the moment, the doors are one way - you can progress to the next level but if you turn around - you can't go back to the previous level.

Make sure that the player doesn't spawn on this point.

You will need to add some code to the player to alter their spawn point.... so they don't spawn back at the beginning of the level when they reenter level 1 or level 2

**Comment by Dylanimal** [comment]
Done
