### ISSUE TITLE
Add something to indicate doors that you can go through

### ISSUE THREAD

**Issue by jeffaroundtheworld** [jeffaroundtheworld/2024gamecollab#95]
Feedback from play tester was that it is not obvious that you can go through the locked door on level one and you need to find the key... add sign, or chain, or message popup that indicates this door can be activated.

Also, the doors to go from level 1 to 2 and level 2 to 3 are not differentiated from other non-passible doors.  Can we differentiate them somehow?  Maybe use the light mechanic like we did with the key?

**Comment by Dylanimal** [comment]
I added a red exit sign above the door and had a friend test it and was able to find where to go

**Comment by Dylanimal** [comment]
Lights added to all doors and places which might be hard to find
